<a href="https://colab.research.google.com/github/xuandy05/Python-A.I./blob/master/Pandas_Practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
pd.set_option('display.expand_frame_repr', False)

url = "https://pynative.com/wp-content/uploads/2019/01/Automobile_data.csv"

1. Using the url provided use the read_csv function to create a data frame.
print the first 5 elements using the head() function, and the last 5 elements using the tail function

In [0]:
df = pd.read_csv(url)
print(df.head())
print(df.tail())

   index      company   body-style  wheel-base  length engine-type num-of-cylinders  horsepower  average-mileage    price
0      0  alfa-romero  convertible        88.6   168.8        dohc             four         111               21  13495.0
1      1  alfa-romero  convertible        88.6   168.8        dohc             four         111               21  16500.0
2      2  alfa-romero    hatchback        94.5   171.2        ohcv              six         154               19  16500.0
3      3         audi        sedan        99.8   176.6         ohc             four         102               24  13950.0
4      4         audi        sedan        99.4   176.6         ohc             five         115               18  17450.0
    index     company body-style  wheel-base  length engine-type num-of-cylinders  horsepower  average-mileage    price
56     81  volkswagen      sedan        97.3   171.7         ohc             four          85               27   7975.0
57     82  volkswagen      sedan        97.3   171.7         ohc             four          52               37   7995.0
58     86  volkswagen      sedan        97.3   171.7         ohc             four         100               26   9995.0
59     87       volvo      sedan       104.3   188.8         ohc             four         114               23  12940.0
60     88       volvo      wagon       104.3   188.8         ohc             four         114               23  13415.0

2. Now use boolean indexing to find the longest car in the set, then find the cheapest car in the set.

In [0]:
longest = max(df['length']) 
longest_car = df[df['length'] == longest]
print(longest_car)
cheapest = min(df['price'])
cheapest_car = df[df['price'] == cheapest]
print(cheapest_car)

    index        company body-style  wheel-base  length engine-type num-of-cylinders  horsepower  average-mileage    price
34     46  mercedes-benz      sedan       120.9   208.1        ohcv            eight         184               14  40960.0
    index    company body-style  wheel-base  length engine-type num-of-cylinders  horsepower  average-mileage   price
13     16  chevrolet  hatchback        88.4   141.1           l            three          48               47  5151.0

3. Print the number of cars for each company

In [0]:
x = df[df['company'] == 'alfa-romero']
x.size/10

3.0

4. Add a new column to the end of the Dataframe. The name of this column is 'horse price' and the value of this column is equal to the price divided its horse power. (price/horsepower)

In [0]:
df.insert(10, "horse price", df['price']/df['horsepower'], True)
df

    index        company   body-style  wheel-base  length engine-type num-of-cylinders  horsepower  average-mileage    price  horse price
0       0    alfa-romero  convertible        88.6   168.8        dohc             four         111               21  13495.0   121.576577
1       1    alfa-romero  convertible        88.6   168.8        dohc             four         111               21  16500.0   148.648649
2       2    alfa-romero    hatchback        94.5   171.2        ohcv              six         154               19  16500.0   107.142857
3       3           audi        sedan        99.8   176.6         ohc             four         102               24  13950.0   136.764706
4       4           audi        sedan        99.4   176.6         ohc             five         115               18  17450.0   151.739130
5       5           audi        sedan        99.8   177.3         ohc             five         110               19  15250.0   138.636364
6       6           audi        wagon       105.8   192.7         ohc             five         110               19  18920.0   172.000000
7       9            bmw        sedan       101.2   176.8         ohc             four         101               23  16430.0   162.673267
8      10            bmw        sedan       101.2   176.8         ohc             four         101               23  16925.0   167.574257
9      11            bmw        sedan       101.2   176.8         ohc              six         121               21  20970.0   173.305785
10     13            bmw        sedan       103.5   189.0         ohc              six         182               16  30760.0   169.010989
11     14            bmw        sedan       103.5   193.8         ohc              six         182               16  41315.0   227.005495
12     15            bmw        sedan       110.0   197.0         ohc              six         182               15  36880.0   202.637363
13     16      chevrolet    hatchback        88.4   141.1           l            three          48               47   5151.0   107.312500
14     17      chevrolet    hatchback        94.5   155.9         ohc             four          70               38   6295.0    89.928571
15     18      chevrolet        sedan        94.5   158.8         ohc             four          70               38   6575.0    93.928571
16     19          dodge    hatchback        93.7   157.3         ohc             four          68               31   6377.0    93.779412
17     20          dodge    hatchback        93.7   157.3         ohc             four          68               31   6229.0    91.602941
18     27          honda        wagon        96.5   157.1         ohc             four          76               30   7295.0    95.986842
19     28          honda        sedan        96.5   175.4         ohc             four         101               24  12945.0   128.168317
20     29          honda        sedan        96.5   169.1         ohc             four         100               25  10345.0   103.450000
21     30          isuzu        sedan        94.3   170.7         ohc             four          78               24   6785.0    86.987179
22     31          isuzu        sedan        94.5   155.9         ohc             four          70               38      NaN          NaN
23     32          isuzu        sedan        94.5   155.9         ohc             four          70               38      NaN          NaN
24     33         jaguar        sedan       113.0   199.6        dohc              six         176               15  32250.0   183.238636
25     34         jaguar        sedan       113.0   199.6        dohc              six         176               15  35550.0   201.988636
26     35         jaguar        sedan       102.0   191.7        ohcv           twelve         262               13  36000.0   137.404580
27     36          mazda    hatchback        93.1   159.1         ohc             four          68               30   5195.0    76.397059
28     37          mazda    hatchback        93.1   159.1         ohc             four          68               31   6095.0    89.632353
29     38          mazda    hatchback        93.1   159.1         ohc             four          68               31   6795.0    99.926471
..    ...            ...          ...         ...     ...         ...              ...         ...              ...      ...          ...
31     43          mazda        sedan       104.9   175.0         ohc             four          72               31  18344.0   254.777778
32     44  mercedes-benz        sedan       110.0   190.9         ohc             five         123               22  25552.0   207.739837
33     45  mercedes-benz        wagon       110.0   190.9         ohc             five         123               22  28248.0   229.658537
34     46  mercedes-benz        sedan       120.9   208.1        ohcv            eight         184               14  40960.0   222.608696
35     47  mercedes-benz      hardtop       112.0   199.2        ohcv            eight         184               14  45400.0   246.739130
36     49     mitsubishi    hatchback        93.7   157.3         ohc             four          68               37   5389.0    79.250000
37     50     mitsubishi    hatchback        93.7   157.3         ohc             four          68               31   6189.0    91.014706
38     51     mitsubishi        sedan        96.3   172.4         ohc             four          88               25   6989.0    79.420455
39     52     mitsubishi        sedan        96.3   172.4         ohc             four          88               25   8189.0    93.056818
40     53         nissan        sedan        94.5   165.3         ohc             four          55               45   7099.0   129.072727
41     54         nissan        sedan        94.5   165.3         ohc             four          69               31   6649.0    96.362319
42     55         nissan        sedan        94.5   165.3         ohc             four          69               31   6849.0    99.260870
43     56         nissan        wagon        94.5   170.2         ohc             four          69               31   7349.0   106.507246
44     57         nissan        sedan       100.4   184.6        ohcv              six         152               19  13499.0    88.809211
45     61        porsche      hardtop        89.5   168.9        ohcf              six         207               17  34028.0   164.386473
46     62        porsche  convertible        89.5   168.9        ohcf              six         207               17  37028.0   178.879227
47     63        porsche    hatchback        98.4   175.7       dohcv            eight         288               17      NaN          NaN
48     66         toyota    hatchback        95.7   158.7         ohc             four          62               35   5348.0    86.258065
49     67         toyota    hatchback        95.7   158.7         ohc             four          62               31   6338.0   102.225806
50     68         toyota    hatchback        95.7   158.7         ohc             four          62               31   6488.0   104.645161
51     69         toyota        wagon        95.7   169.7         ohc             four          62               31   6918.0   111.580645
52     70         toyota        wagon        95.7   169.7         ohc             four          62               27   7898.0   127.387097
53     71         toyota        wagon        95.7   169.7         ohc             four          62               27   8778.0   141.580645
54     79         toyota        wagon       104.5   187.8        dohc              six         156               19  15750.0   100.961538
55     80     volkswagen        sedan        97.3   171.7         ohc             four          52               37   7775.0   149.519231
56     81     volkswagen        sedan        97.3   171.7         ohc             four          85               27   7975.0    93.823529
57     82     volkswagen        sedan        97.3   171.7         ohc             four          52               37   7995.0   153.750000
58     86     volkswagen        sedan        97.3   171.7         ohc             four         100               26   9995.0    99.950000
59     87          volvo        sedan       104.3   188.8         ohc             four         114               23  12940.0   113.508772
60     88          volvo        wagon       104.3   188.8         ohc             four         114               23  13415.0   117.675439

[61 rows x 11 columns]

### BONUS
5. Delete any rows that contains the value NaN

In [0]:
df = df.dropna()
df.reset_index(drop = True)

    index        company   body-style  wheel-base  length engine-type num-of-cylinders  horsepower  average-mileage    price  horse price
0       0    alfa-romero  convertible        88.6   168.8        dohc             four         111               21  13495.0   121.576577
1       1    alfa-romero  convertible        88.6   168.8        dohc             four         111               21  16500.0   148.648649
2       2    alfa-romero    hatchback        94.5   171.2        ohcv              six         154               19  16500.0   107.142857
3       3           audi        sedan        99.8   176.6         ohc             four         102               24  13950.0   136.764706
4       4           audi        sedan        99.4   176.6         ohc             five         115               18  17450.0   151.739130
5       5           audi        sedan        99.8   177.3         ohc             five         110               19  15250.0   138.636364
6       6           audi        wagon       105.8   192.7         ohc             five         110               19  18920.0   172.000000
7       9            bmw        sedan       101.2   176.8         ohc             four         101               23  16430.0   162.673267
8      10            bmw        sedan       101.2   176.8         ohc             four         101               23  16925.0   167.574257
9      11            bmw        sedan       101.2   176.8         ohc              six         121               21  20970.0   173.305785
10     13            bmw        sedan       103.5   189.0         ohc              six         182               16  30760.0   169.010989
11     14            bmw        sedan       103.5   193.8         ohc              six         182               16  41315.0   227.005495
12     15            bmw        sedan       110.0   197.0         ohc              six         182               15  36880.0   202.637363
13     16      chevrolet    hatchback        88.4   141.1           l            three          48               47   5151.0   107.312500
14     17      chevrolet    hatchback        94.5   155.9         ohc             four          70               38   6295.0    89.928571
15     18      chevrolet        sedan        94.5   158.8         ohc             four          70               38   6575.0    93.928571
16     19          dodge    hatchback        93.7   157.3         ohc             four          68               31   6377.0    93.779412
17     20          dodge    hatchback        93.7   157.3         ohc             four          68               31   6229.0    91.602941
18     27          honda        wagon        96.5   157.1         ohc             four          76               30   7295.0    95.986842
19     28          honda        sedan        96.5   175.4         ohc             four         101               24  12945.0   128.168317
20     29          honda        sedan        96.5   169.1         ohc             four         100               25  10345.0   103.450000
21     30          isuzu        sedan        94.3   170.7         ohc             four          78               24   6785.0    86.987179
22     33         jaguar        sedan       113.0   199.6        dohc              six         176               15  32250.0   183.238636
23     34         jaguar        sedan       113.0   199.6        dohc              six         176               15  35550.0   201.988636
24     35         jaguar        sedan       102.0   191.7        ohcv           twelve         262               13  36000.0   137.404580
25     36          mazda    hatchback        93.1   159.1         ohc             four          68               30   5195.0    76.397059
26     37          mazda    hatchback        93.1   159.1         ohc             four          68               31   6095.0    89.632353
27     38          mazda    hatchback        93.1   159.1         ohc             four          68               31   6795.0    99.926471
28     39          mazda    hatchback        95.3   169.0       rotor              two         101               17  11845.0   117.277228
29     43          mazda        sedan       104.9   175.0         ohc             four          72               31  18344.0   254.777778
30     44  mercedes-benz        sedan       110.0   190.9         ohc             five         123               22  25552.0   207.739837
31     45  mercedes-benz        wagon       110.0   190.9         ohc             five         123               22  28248.0   229.658537
32     46  mercedes-benz        sedan       120.9   208.1        ohcv            eight         184               14  40960.0   222.608696
33     47  mercedes-benz      hardtop       112.0   199.2        ohcv            eight         184               14  45400.0   246.739130
34     49     mitsubishi    hatchback        93.7   157.3         ohc             four          68               37   5389.0    79.250000
35     50     mitsubishi    hatchback        93.7   157.3         ohc             four          68               31   6189.0    91.014706
36     51     mitsubishi        sedan        96.3   172.4         ohc             four          88               25   6989.0    79.420455
37     52     mitsubishi        sedan        96.3   172.4         ohc             four          88               25   8189.0    93.056818
38     53         nissan        sedan        94.5   165.3         ohc             four          55               45   7099.0   129.072727
39     54         nissan        sedan        94.5   165.3         ohc             four          69               31   6649.0    96.362319
40     55         nissan        sedan        94.5   165.3         ohc             four          69               31   6849.0    99.260870
41     56         nissan        wagon        94.5   170.2         ohc             four          69               31   7349.0   106.507246
42     57         nissan        sedan       100.4   184.6        ohcv              six         152               19  13499.0    88.809211
43     61        porsche      hardtop        89.5   168.9        ohcf              six         207               17  34028.0   164.386473
44     62        porsche  convertible        89.5   168.9        ohcf              six         207               17  37028.0   178.879227
45     66         toyota    hatchback        95.7   158.7         ohc             four          62               35   5348.0    86.258065
46     67         toyota    hatchback        95.7   158.7         ohc             four          62               31   6338.0   102.225806
47     68         toyota    hatchback        95.7   158.7         ohc             four          62               31   6488.0   104.645161
48     69         toyota        wagon        95.7   169.7         ohc             four          62               31   6918.0   111.580645
49     70         toyota        wagon        95.7   169.7         ohc             four          62               27   7898.0   127.387097
50     71         toyota        wagon        95.7   169.7         ohc             four          62               27   8778.0   141.580645
51     79         toyota        wagon       104.5   187.8        dohc              six         156               19  15750.0   100.961538
52     80     volkswagen        sedan        97.3   171.7         ohc             four          52               37   7775.0   149.519231
53     81     volkswagen        sedan        97.3   171.7         ohc             four          85               27   7975.0    93.823529
54     82     volkswagen        sedan        97.3   171.7         ohc             four          52               37   7995.0   153.750000
55     86     volkswagen        sedan        97.3   171.7         ohc             four         100               26   9995.0    99.950000
56     87          volvo        sedan       104.3   188.8         ohc             four         114               23  12940.0   113.508772
57     88          volvo        wagon       104.3   188.8         ohc             four         114               23  13415.0   117.675439

6. Repalce all NaN values with the value 1

In [0]:
import numpy as np
df = df.replace(np.nan, 1)
df
# df = fillna(1)

    index        company   body-style  wheel-base  length engine-type num-of-cylinders  horsepower  average-mileage    price  horse price
0       0    alfa-romero  convertible        88.6   168.8        dohc             four         111               21  13495.0   121.576577
1       1    alfa-romero  convertible        88.6   168.8        dohc             four         111               21  16500.0   148.648649
2       2    alfa-romero    hatchback        94.5   171.2        ohcv              six         154               19  16500.0   107.142857
3       3           audi        sedan        99.8   176.6         ohc             four         102               24  13950.0   136.764706
4       4           audi        sedan        99.4   176.6         ohc             five         115               18  17450.0   151.739130
5       5           audi        sedan        99.8   177.3         ohc             five         110               19  15250.0   138.636364
6       6           audi        wagon       105.8   192.7         ohc             five         110               19  18920.0   172.000000
7       9            bmw        sedan       101.2   176.8         ohc             four         101               23  16430.0   162.673267
8      10            bmw        sedan       101.2   176.8         ohc             four         101               23  16925.0   167.574257
9      11            bmw        sedan       101.2   176.8         ohc              six         121               21  20970.0   173.305785
10     13            bmw        sedan       103.5   189.0         ohc              six         182               16  30760.0   169.010989
11     16      chevrolet    hatchback        88.4   141.1           l            three          48               47   5151.0   107.312500
12     17      chevrolet    hatchback        94.5   155.9         ohc             four          70               38   6295.0    89.928571
13     18      chevrolet        sedan        94.5   158.8         ohc             four          70               38   6575.0    93.928571
14     19          dodge    hatchback        93.7   157.3         ohc             four          68               31   6377.0    93.779412
15     20          dodge    hatchback        93.7   157.3         ohc             four          68               31   6229.0    91.602941
16     27          honda        wagon        96.5   157.1         ohc             four          76               30   7295.0    95.986842
17     28          honda        sedan        96.5   175.4         ohc             four         101               24  12945.0   128.168317
18     29          honda        sedan        96.5   169.1         ohc             four         100               25  10345.0   103.450000
19     30          isuzu        sedan        94.3   170.7         ohc             four          78               24   6785.0    86.987179
20     36          mazda    hatchback        93.1   159.1         ohc             four          68               30   5195.0    76.397059
21     37          mazda    hatchback        93.1   159.1         ohc             four          68               31   6095.0    89.632353
22     38          mazda    hatchback        93.1   159.1         ohc             four          68               31   6795.0    99.926471
23     39          mazda    hatchback        95.3   169.0       rotor              two         101               17  11845.0   117.277228
24     43          mazda        sedan       104.9   175.0         ohc             four          72               31  18344.0   254.777778
25     44  mercedes-benz        sedan       110.0   190.9         ohc             five         123               22  25552.0   207.739837
26     45  mercedes-benz        wagon       110.0   190.9         ohc             five         123               22  28248.0   229.658537
27     49     mitsubishi    hatchback        93.7   157.3         ohc             four          68               37   5389.0    79.250000
28     50     mitsubishi    hatchback        93.7   157.3         ohc             four          68               31   6189.0    91.014706
29     51     mitsubishi        sedan        96.3   172.4         ohc             four          88               25   6989.0    79.420455
30     52     mitsubishi        sedan        96.3   172.4         ohc             four          88               25   8189.0    93.056818
31     53         nissan        sedan        94.5   165.3         ohc             four          55               45   7099.0   129.072727
32     54         nissan        sedan        94.5   165.3         ohc             four          69               31   6649.0    96.362319
33     55         nissan        sedan        94.5   165.3         ohc             four          69               31   6849.0    99.260870
34     56         nissan        wagon        94.5   170.2         ohc             four          69               31   7349.0   106.507246
35     57         nissan        sedan       100.4   184.6        ohcv              six         152               19  13499.0    88.809211
36     66         toyota    hatchback        95.7   158.7         ohc             four          62               35   5348.0    86.258065
37     67         toyota    hatchback        95.7   158.7         ohc             four          62               31   6338.0   102.225806
38     68         toyota    hatchback        95.7   158.7         ohc             four          62               31   6488.0   104.645161
39     69         toyota        wagon        95.7   169.7         ohc             four          62               31   6918.0   111.580645
40     70         toyota        wagon        95.7   169.7         ohc             four          62               27   7898.0   127.387097
41     71         toyota        wagon        95.7   169.7         ohc             four          62               27   8778.0   141.580645
42     79         toyota        wagon       104.5   187.8        dohc              six         156               19  15750.0   100.961538
43     80     volkswagen        sedan        97.3   171.7         ohc             four          52               37   7775.0   149.519231
44     81     volkswagen        sedan        97.3   171.7         ohc             four          85               27   7975.0    93.823529
45     82     volkswagen        sedan        97.3   171.7         ohc             four          52               37   7995.0   153.750000
46     86     volkswagen        sedan        97.3   171.7         ohc             four         100               26   9995.0    99.950000
47     87          volvo        sedan       104.3   188.8         ohc             four         114               23  12940.0   113.508772
48     88          volvo        wagon       104.3   188.8         ohc             four         114               23  13415.0   117.675439

In [0]:
describe = df.describe()
features = ['wheel-base', 'length', 'horsepower', 'average-mileage', 'price', 'horse price']
for each in features:
  IQR = describe[each]['75%'] - describe[each]['25%']
  df = df[df[each] < describe[each]['75%'] + 1.5 * IQR]
  df = df[df[each] > describe[each]['25%'] - 1.5 * IQR]
df = df.reset_index(drop = True)
df

    index        company   body-style  wheel-base  length engine-type num-of-cylinders  horsepower  average-mileage    price  horse price
0       0    alfa-romero  convertible        88.6   168.8        dohc             four         111               21  13495.0   121.576577
1       1    alfa-romero  convertible        88.6   168.8        dohc             four         111               21  16500.0   148.648649
2       2    alfa-romero    hatchback        94.5   171.2        ohcv              six         154               19  16500.0   107.142857
3       3           audi        sedan        99.8   176.6         ohc             four         102               24  13950.0   136.764706
4       4           audi        sedan        99.4   176.6         ohc             five         115               18  17450.0   151.739130
5       5           audi        sedan        99.8   177.3         ohc             five         110               19  15250.0   138.636364
6       6           audi        wagon       105.8   192.7         ohc             five         110               19  18920.0   172.000000
7       9            bmw        sedan       101.2   176.8         ohc             four         101               23  16430.0   162.673267
8      10            bmw        sedan       101.2   176.8         ohc             four         101               23  16925.0   167.574257
9      11            bmw        sedan       101.2   176.8         ohc              six         121               21  20970.0   173.305785
10     13            bmw        sedan       103.5   189.0         ohc              six         182               16  30760.0   169.010989
11     16      chevrolet    hatchback        88.4   141.1           l            three          48               47   5151.0   107.312500
12     17      chevrolet    hatchback        94.5   155.9         ohc             four          70               38   6295.0    89.928571
13     18      chevrolet        sedan        94.5   158.8         ohc             four          70               38   6575.0    93.928571
14     19          dodge    hatchback        93.7   157.3         ohc             four          68               31   6377.0    93.779412
15     20          dodge    hatchback        93.7   157.3         ohc             four          68               31   6229.0    91.602941
16     27          honda        wagon        96.5   157.1         ohc             four          76               30   7295.0    95.986842
17     28          honda        sedan        96.5   175.4         ohc             four         101               24  12945.0   128.168317
18     29          honda        sedan        96.5   169.1         ohc             four         100               25  10345.0   103.450000
19     30          isuzu        sedan        94.3   170.7         ohc             four          78               24   6785.0    86.987179
20     36          mazda    hatchback        93.1   159.1         ohc             four          68               30   5195.0    76.397059
21     37          mazda    hatchback        93.1   159.1         ohc             four          68               31   6095.0    89.632353
22     38          mazda    hatchback        93.1   159.1         ohc             four          68               31   6795.0    99.926471
23     39          mazda    hatchback        95.3   169.0       rotor              two         101               17  11845.0   117.277228
24     43          mazda        sedan       104.9   175.0         ohc             four          72               31  18344.0   254.777778
25     44  mercedes-benz        sedan       110.0   190.9         ohc             five         123               22  25552.0   207.739837
26     45  mercedes-benz        wagon       110.0   190.9         ohc             five         123               22  28248.0   229.658537
27     49     mitsubishi    hatchback        93.7   157.3         ohc             four          68               37   5389.0    79.250000
28     50     mitsubishi    hatchback        93.7   157.3         ohc             four          68               31   6189.0    91.014706
29     51     mitsubishi        sedan        96.3   172.4         ohc             four          88               25   6989.0    79.420455
30     52     mitsubishi        sedan        96.3   172.4         ohc             four          88               25   8189.0    93.056818
31     53         nissan        sedan        94.5   165.3         ohc             four          55               45   7099.0   129.072727
32     54         nissan        sedan        94.5   165.3         ohc             four          69               31   6649.0    96.362319
33     55         nissan        sedan        94.5   165.3         ohc             four          69               31   6849.0    99.260870
34     56         nissan        wagon        94.5   170.2         ohc             four          69               31   7349.0   106.507246
35     57         nissan        sedan       100.4   184.6        ohcv              six         152               19  13499.0    88.809211
36     66         toyota    hatchback        95.7   158.7         ohc             four          62               35   5348.0    86.258065
37     67         toyota    hatchback        95.7   158.7         ohc             four          62               31   6338.0   102.225806
38     68         toyota    hatchback        95.7   158.7         ohc             four          62               31   6488.0   104.645161
39     69         toyota        wagon        95.7   169.7         ohc             four          62               31   6918.0   111.580645
40     70         toyota        wagon        95.7   169.7         ohc             four          62               27   7898.0   127.387097
41     71         toyota        wagon        95.7   169.7         ohc             four          62               27   8778.0   141.580645
42     79         toyota        wagon       104.5   187.8        dohc              six         156               19  15750.0   100.961538
43     80     volkswagen        sedan        97.3   171.7         ohc             four          52               37   7775.0   149.519231
44     81     volkswagen        sedan        97.3   171.7         ohc             four          85               27   7975.0    93.823529
45     82     volkswagen        sedan        97.3   171.7         ohc             four          52               37   7995.0   153.750000
46     86     volkswagen        sedan        97.3   171.7         ohc             four         100               26   9995.0    99.950000
47     87          volvo        sedan       104.3   188.8         ohc             four         114               23  12940.0   113.508772
48     88          volvo        wagon       104.3   188.8         ohc             four         114               23  13415.0   117.675439